/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type {ColumnType} from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface PosttopCategory {
  id: Generated<number>;
  name: string;
}

export interface PosttopChannel {
  id: Generated<number>;
  name: string;
  yt_id: string;
}

export interface PosttopIsMusicVideo {
  created_at: Generated<Timestamp>;
  is_music: boolean;
  submitted_by_id: number;
  video_id: Int8;
}

export interface PosttopListened {
  listened_at: Generated<Timestamp>;
  user_id: number;
  video_id: Int8;
}

export interface PosttopMainCategory {
  id: number;
  name: string;
}

export interface PosttopNerResult {
  created_at: Generated<Timestamp>;
  language: string;
  ner_result: Json;
  submitted_by_id: number;
  video_id: Int8;
}

export interface PosttopRole {
  id: Generated<number>;
  name: string;
}

export interface PosttopUser {
  handle: Generated<string>;
  id: Generated<number>;
  password_hash: string;
  username: string;
}

export interface PosttopUserRole {
  role_id: number;
  user_id: number;
}

export interface PosttopVideo {
  channel_id: number | null;
  default_language: string;
  duration: number;
  id: Generated<Int8>;
  main_category_id: number | null;
  yt_id: string;
}

export interface PosttopVideoCategory {
  category_id: number;
  video_id: Int8;
}

export interface PosttopVideoMetadata {
  description: string | null;
  language: string;
  title: string;
  video_id: Int8;
}

export interface DB {
  "posttop.category": PosttopCategory;
  "posttop.channel": PosttopChannel;
  "posttop.is_music_video": PosttopIsMusicVideo;
  "posttop.listened": PosttopListened;
  "posttop.main_category": PosttopMainCategory;
  "posttop.ner_result": PosttopNerResult;
  "posttop.role": PosttopRole;
  "posttop.user": PosttopUser;
  "posttop.user_role": PosttopUserRole;
  "posttop.video": PosttopVideo;
  "posttop.video_category": PosttopVideoCategory;
  "posttop.video_metadata": PosttopVideoMetadata;
}
