/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type {ColumnType} from "kysely";
import type {ChannelID, ChannelYTID, VideoID, VideoYTID} from "./override";

export enum ModelType {
  GENRE_CLASSIFIER = "genre_classifier",
  IS_MUSIC_CLASSIFIER = "is_music_classifier",
  NER = "ner",
}

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface Category {
  id: Generated<number>;
  name: string;
}

export interface Channel {
  id: Generated<ChannelID>;
  name: string;
  yt_id: ChannelYTID;
}

export interface IsMusicVideo {
  created_at: Generated<Timestamp>;
  is_music: boolean;
  submitted_by_id: number;
  video_id: VideoID;
}

export interface IsMusicVideoPrediction {
  created_at: Generated<Timestamp>;
  is_music: boolean;
  submitted_by_id: number;
  video_id: VideoID;
}

export interface Listened {
  listened_at: Generated<Timestamp>;
  user_id: number;
  video_id: VideoID;
}

export interface MainCategory {
  id: number;
  name: string;
}

export interface Model {
  id: Generated<number>;
  type: ModelType;
  version: string;
}

export interface NerResult {
  created_at: Generated<Timestamp>;
  language: string;
  ner_result: Json;
  submitted_by_id: number;
  video_id: VideoID;
}

export interface Role {
  id: Generated<number>;
  name: string;
}

export interface Session {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface User {
  better_auth_id: string | null;
  handle: string | null;
  id: Generated<number>;
  password_hash: string | null;
  username: string | null;
}

export interface UserBetterAuth {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: boolean;
  id: string;
  image: string | null;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface UserRole {
  role_id: number;
  user_id: number;
}

export interface Verification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface Video {
  channel_id: ChannelID;
  default_language: string;
  duration: number;
  id: Generated<VideoID>;
  main_category_id: number | null;
  yt_id: VideoYTID;
}

export interface VideoCategory {
  category_id: number;
  video_id: VideoID;
}

export interface VideoMetadata {
  description: string | null;
  language: string;
  title: string;
  video_id: VideoID;
}

export interface DB {
  account: Account;
  category: Category;
  channel: Channel;
  is_music_video: IsMusicVideo;
  is_music_video_prediction: IsMusicVideoPrediction;
  listened: Listened;
  main_category: MainCategory;
  model: Model;
  ner_result: NerResult;
  role: Role;
  session: Session;
  user: User;
  user_better_auth: UserBetterAuth;
  user_role: UserRole;
  verification: Verification;
  video: Video;
  video_category: VideoCategory;
  video_metadata: VideoMetadata;
}
